### ISSUE TITLE
iterable autocompletion

### ISSUE THREAD

**Issue by ro0NL** [Haehnchen/idea-php-generics-plugin#14]
would be super nice for this plugin to support autocompletion for `iterable<int, Some>` similar like `Some[]` already works.

That's a huge time saver :)

**Comment by garak** [comment]
I'm wondering why this is still unsupported.
This plugins claims to support phpstan and psalm, but currently it looks like it only supports psalm.

**Comment by orklah** [comment]
> This plugins claims to support phpstan and psalm, but currently it looks like it only supports psalm.

What's that have to do with anything? That syntax is supported by both Psalm an Phpstan

> I'm wondering why this is still unsupported.

This plugin has been really working for a few days now. The readme mention that's a work in progress. Have some patience... or submit a PR

Now that's said, it would be really cool to have this feature!
