### ISSUE TITLE
Doesn't seem to install correctly in PHPStorm 2020.1

### ISSUE THREAD

**Issue by shmax** [Haehnchen/idea-php-generics-plugin#23]
Looks like a great plugin, but maybe I don't quite fathom exactly what is supposed to happen. I began by installing from your website (I downgraded my PHPStorm version from 2020.1 to 2019.3):

![image](https://user-images.githubusercontent.com/773172/80559878-e3025480-8993-11ea-8757-d7cb1ad0099a.png)

![image](https://user-images.githubusercontent.com/773172/80559922-f7465180-8993-11ea-9804-98817ee49ff9.png)

If I open PHPStorm plugins, and search for "phpstan" in the marketplace, I can see it marked as "installed":

![image](https://user-images.githubusercontent.com/773172/80559975-2c52a400-8994-11ea-8a94-17c6772e7608.png)

But I don't see any "PHPStan" section in Settings > Languages & Frameworks > PHP > Quality Tools:

![image](https://user-images.githubusercontent.com/773172/80560029-5a37e880-8994-11ea-858f-8d269a7b30ed.png)

Am I missing something?  Let me know if I can provide any more information. Thanks much.

**Comment by orklah** [comment]
Version 0.5 is still waiting approval from Jetbrains. It should be ok today

**Comment by shmax** [comment]
So why did it install? Or did it not install? If it's not approved, why did it install? If it didn't install, why does PHPStorm mark it as "installed"? Etc...

**Comment by orklah** [comment]
I think you installed version 0.4.

According to https://plugins.jetbrains.com/plugin/12754-phpstan--psalm--generics it's the last available version and there is a warning

> The plugin update is pending JetBrains approval

The PHPStan block is a new feature released only on 0.5

**Comment by shmax** [comment]
I see. It's a bit confusing, isn't it? Well, I'll give it a day or two and try again. Thanks much.
