### ISSUE TITLE
Error validating psalm path on windows

### ISSUE THREAD

**Issue by dbrekelmans** [Haehnchen/idea-php-generics-plugin#26]
I'm eager to use the psalm inspection added in 0.5.0, thanks for your work on this.

Unfortunately I'm getting an error when setting the local psalm path. I'm on Windows 10, which I think causes the issue compared to Linux. I don't have php installed on windows; I use Debian 10 with php installed through WSL. I don't think this affects the plugin, since I have my PHP interpreter set correctly to Debian via "Languages & Frameworks > PHP"

When clicking "Validate" after setting the path, I get the following error message at the bottom of the window:
`Cannot run program "C:\Users\<redacted>\vendor\vimeo\psalm\psalm" (in directory "C:\Users\<redacted>"): CreateProcess error=193, %1 is not a valid Win32 application`

If I press "Apply" anyway and enable the inspection, it shows the actual exception name in a popup balloon when it tries to inspect the file: `com.intellij.execution.process.ProcessNotCreatedException`

**Comment by orklah** [comment]
I had the same error on 0.5.0, seems like validation is now working when selecting the psalm.bat file on 0.7.0 (I thought I already tried the .bat on 0.5.0 but I'm not so sure anymore)

**Comment by dbrekelmans** [comment]
For me the error still persists on 0.7.0

**Comment by orklah** [comment]
Even with the .bat file?

**Comment by dbrekelmans** [comment]
Yep, I have `vendor\vimeo\psalm\psalm.bat` selected.

**Comment by orklah** [comment]
Weird indeed...
