### ISSUE TITLE
Psalm / PhpStan config path

### ISSUE THREAD

**Issue by voku** [Haehnchen/idea-php-generics-plugin#42]
First, many thanks for this plugin. :+1: 

Could you add a config path for Pslam and PhpStan, so that I can choose a different config file? For example: we use different config files for new and old files, so that new modules are a bit stricter than older code and this config files are not in the root directory of the project.

**Comment by ndench** [comment]
Another use case is for storing config for different tools in a subdirectory. When you're running a bunch of different tools you end up with the project root being littered with a bunch of different `*.yml`, `*.xml`, `*.neon`, etc config files. I often move this into a `config/` or `qa/` folder to make them easier to find and to tidy up the root.
