### ISSUE TITLE
Duplicated configuration

### ISSUE THREAD

**Issue by dbalabka** [Haehnchen/idea-php-generics-plugin#43]
Each time when you open Psalm configuration window "Local" record will be added:
![image](https://user-images.githubusercontent.com/1269372/81043115-5509fa80-8eba-11ea-8922-92290303eebd.png)

**Comment by jdreesen** [comment]
Duplicate of #31

**Comment by dbalabka** [comment]
@jdreesen thanks. Closing this one as duplicated then
