### ISSUE TITLE
Typehint for classes not working

### ISSUE THREAD

**Issue by oldrichpospisilik** [Haehnchen/idea-php-generics-plugin#45]
Typehinting functions with class-string keyword working perfectly:

![works-great](https://user-images.githubusercontent.com/28293297/81802527-89af2f00-9516-11ea-9995-b3a569f30235.png)

Typehinting classes is not working. Its not implemented yet or i have a typo in my code?

![not-working](https://user-images.githubusercontent.com/28293297/81802539-8ddb4c80-9516-11ea-9326-42463c0bfd1f.png)

Thank you very much. BTW amazing job.

**Comment by oldrichpospisilik** [comment]
![array](https://user-images.githubusercontent.com/28293297/81818733-b1aa8c80-952e-11ea-80f6-ce558a80a0ce.png)

**Comment by simPod** [comment]
It's WIP https://github.com/Haehnchen/idea-php-generics-plugin/issues/14

**Comment by voku** [comment]
```@psalm-return array<int,T>``` is currently not supported, or? Do I need to change something in the code? https://github.com/voku/phpstorm_issue_53352/blob/master/src/Framework/ActiveRecord/ManagedFactory.php#L124
