### ISSUE TITLE
Problem with PhpStorm 2020.2 EAP - PS-202.5958.28

### ISSUE THREAD

**Issue by matiux** [Haehnchen/idea-php-generics-plugin#52]
com.intellij.openapi.extensions.ExtensionException: Extension class de.espend.idea.php.quality.phpstan.configuration.PhpStanValidatorConfigurationManager does not implement interface com.jetbrains.php.config.interpreters.PhpInterpretersStateListener (adapter=ExtensionComponentAdapter(impl=de.espend.idea.php.quality.phpstan.configuration.PhpStanValidatorConfigurationManager, plugin=PluginDescriptor(name=PHPStan / Psalm / Generics, id=de.espend.idea.php.generics, path=/home/iux/.local/share/JetBrains/PhpStorm2020.2/PHP Generics, version=0.7.0)))

PhpStorm 2020.2 EAP
Build #PS-202.5958.28, built on June 25, 2020
PhpStorm EAP User
Expiration date: July 25, 2020
Runtime version: 11.0.7+10-b944.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.7.6-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Jenkins Control Plugin, Scratch, String Manipulation, com.alayouni.ansiHighlight, com.chrisrm.idea.MaterialThemeUI, com.github.leomillon.uuidgenerator, com.jonathonstaff.ideaascii, com.mallowigi, de.netnexus.camelcaseplugin, ms.konovalov.intellij.hidpi-profiles, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, org.intellij.RegexpTester, org.zalando.intellij.swagger, intellij.prettierJS, com.aurimasniekis.phppsr4namespacedetector, com.dryabov.phpStorm.phpregexp, de.espend.idea.laravel, de.espend.idea.php.annotation, net.king2500.plugins.PhpAdvancedAutoComplete, de.espend.idea.php.generics, lv.midiana.misc.phpstorm-plugins.deep-keys, fr.adrienbrault.idea.symfony2plugin, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv, org.asciidoctor.intellij.asciidoc
Current Desktop: KDE

**Comment by byanelli** [comment]
I'm getting the same error. I tried one of the inspections offered by this package (class-string) and it didn't seem to work
