### ISSUE TITLE
Read access triggers "readonly" inspection

### ISSUE THREAD

**Issue by apfelbox** [Haehnchen/idea-php-generics-plugin#55]
Hi,

see the screenshot:

![2020-07-24 at 18 42](https://user-images.githubusercontent.com/1032411/88414697-8e794480-cddd-11ea-9dd8-886f7a31cdff.png)

**Comment by b1rdex** [comment]
Same

PhpStorm 2020.2
Build #PS-202.6397.71, built on July 24, 2020
