### ISSUE TITLE
Argument Must not be null

### ISSUE THREAD

**Issue by antonmarin** [Haehnchen/idea-php-generics-plugin#56]
Installed plugin
Set path to phpstan (installed globally using composer)
Enabled inspection

Now on every file edit, i get error
`java.lang.IllegalArgumentException: Argument for @NotNull parameter 'parameter' of com/intellij/execution/configurations/GeneralCommandLine.addParameter must not be null`

What did i missed? Is there any doc of installing plugin?

**Comment by dev-loki** [comment]
Same problem here. Happening with archlinux and even a fresh phpstorm install. Had it with 2020.1 and 2020.2. 
OS: Linux
Java is the JRE version by Jetbrains.

**Comment by kalvisbuls** [comment]
Same issue here with Psalm (installed locally) in PhpStorm 2020.2 (build #PS-202.6397.115).

**Comment by miroslav-chandler** [comment]
Same issue in PhpStorm 2020.2 Build #PS-202.6397.115 on mac os 10.15.4

**Comment by ziegi** [comment]
Same here, 
additionally I get the error "Psalm could not be run."
Downgrade to PhpStorm 2020.1.4 solved the issue

**Comment by Leksat** [comment]
Same issue.
```
PhpStorm 2020.2.2
Build #PS-202.7319.77, built on September 23, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: run.processes.with.pty=TRUE, js.debugger.webconsole=false
Non-Bundled Plugins: com.alicannklc.tailwind, com.vexus2.intellij.openingithub, de.netnexus.camelcaseplugin, cucumber-javascript, intellij.prettierJS, com.intellij.lang.jsgraphql, NEON support, de.espend.idea.php.annotation, de.espend.idea.php.generics, ru.adelf.idea.dotenv
```
