### ISSUE TITLE
Plugin seems to be passing the wrong arguments to phpstan when analysing a source file

### ISSUE THREAD

**Issue by xico42** [Haehnchen/idea-php-generics-plugin#57]
I'm using a remote interpreter, and in my setup I get the following error from logs

```
17:58	PHPStan
				phpstan: Can not correctly run the tool with parameters:
				analyse
				--error-format=checkstyle
				null
				Possible tool process hangup after 5 sec.
```

The plugin seems to be executing phpstan passing null as an argument for phpstan.

My phpstan setup is already validated in the IDE. The same happens if I increase timeout.

**Comment by Adirelle** [comment]
I have the same issue using a *remote interpreter*. Moreover, when it actually works, the errors are not reported in the right files. It seems the plugin does handle the path mappings very well.
